### ISSUE TITLE
cannot get it running

### ISSUE THREAD

**Issue by Electogenius** [liimee/another-nothing#4]
My brain is square and I could not get this masterpiece to run.

Because my computer said some modules (I think the crypto one and some others) are deprecated or smth a couple weeks ago when I spent about 45 minutes racking my brain and googling nonsense.

So uh, can you host it somewhere like replit or something?

**Comment by liimee** [comment]
> So uh, can you host it somewhere like replit or something?

I probably can but not sure how to do it...

I also struggled when trying to install it on another machine, but installing some packages (that's why I added *`... and some other stuff probably`* on the readme) fixed it, so uh can you give me the (bundler) logs?

**Comment by Electogenius** [comment]
Here’s the logs (don’t make any sense to me as I don’t know anything about gems and stuff
```
eg@computer another-nothing % sudo bundle
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break thisapplication for all non-root users on this machine.
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Using bundler 2.3.4
Using jwt 2.3.0
Using ruby2_keywords 0.0.5
Using sequel 5.50.0
Using rack 2.2.3
Using tilt 2.0.10
Fetching sqlite3 1.4.2
Fetching kgio 2.11.4
Fetching raindrops 0.20.0
Fetching bcrypt 3.1.16
Using rack-protection 2.1.0
Fetching eventmachine 1.2.7
Using mustermann 1.1.1
Using sinatra 2.1.0
Installing bcrypt 3.1.16 with native extensions
Installing kgio 2.11.4 with native extensions
Installing sqlite3 1.4.2 with native extensions
Installing raindrops 0.20.0 with native extensions
Installing eventmachine 1.2.7 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/bcrypt-3.1.16/ext/mri
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20220114-16522-l8p3aw.rb
extconf.rb
creating Makefile

current directory: /Library/Ruby/Gems/2.6.0/gems/bcrypt-3.1.16/ext/mri
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.6.0/gems/bcrypt-3.1.16/ext/mri
make "DESTDIR="
make: *** No rule to make target
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin21/ruby/config.h',
needed by `bcrypt_ext.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/bcrypt-3.1.16 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-21/2.6.0/bcrypt-3.1.16/gem_make.out

  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:99:in `run'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:51:in `block in
make'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:43:in `each'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:43:in `make'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:62:in
`block in build'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:29:in
`build'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:185:in `block in
build_extension'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:181:in
`build_extension'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:229:in `block in
build_extensions'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:226:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:226:in
`build_extensions'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/installer.rb:830:in
`build_extensions'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.4/lib/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.4/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.4/lib/bundler/source/rubygems.rb:204:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.4/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.4/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.4/lib/bundler/worker.rb:62:in `apply_func'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.4/lib/bundler/worker.rb:57:in `block in process_queue'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.4/lib/bundler/worker.rb:54:in `loop'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.4/lib/bundler/worker.rb:54:in `process_queue'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.4/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing bcrypt (3.1.16), and Bundler cannot continue.

In Gemfile:
  bcrypt
```
Actually now I’m starting to think if I should have modified a config file

**Comment by liimee** [comment]
ah yes it's bcrypt
~~I guess I'll just look for alternatives~~[Vagrant](https://www.vagrantup.com/) is interesting

> Actually now I’m starting to think if I should have modified a config file

nah

edit: see #5

**Comment by Electogenius** [comment]
but still brain too small.
